# Generated by Django 5.2.6 on 2026-04-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_leadrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadrequest',
            name='source',
            field=models.CharField(choices=[('contacts', 'Контакты'), ('about', 'О нас'), ('services', 'Услуги')], max_length=30),
        ),
    ]
