# Generated by Django 5.2.6 on 2026-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_leadrequest_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadrequest',
            name='source',
            field=models.CharField(choices=[('contacts', 'Контакты'), ('about', 'О нас'), ('services', 'Услуги'), ('author_jewelry', 'Авторские украшения')], max_length=30),
        ),
    ]
